#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Publish the Open WebUI frontend (container 8080) through Traefik on a single
# host name. Traefik terminates TLS and transparently proxies the WebSocket
# connection Open WebUI relies on.

import os
import sys
import json

import agent

data = json.load(sys.stdin)

host = data["host"]
h2hs = data.get("http2https", True)
module_id = os.environ["MODULE_ID"]
web_port = os.environ["WEB_PORT"]

route = {
    "instance": module_id,
    "url": "http://127.0.0.1:" + web_port,
    "host": host,
    "http2https": h2hs,
    "lets_encrypt_check": True,
    "lets_encrypt_cleanup": True,
}
if "lets_encrypt" in data:
    route["lets_encrypt"] = data["lets_encrypt"]
agent.set_route(route)
