#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

# Return the current configuration for the UI.

import os
import sys
import json

import agent

host = os.getenv("TRAEFIK_HOST", "")

config = {
    "host": host,
    "http2https": os.getenv("TRAEFIK_HTTP2HTTPS") == "True",
    "lets_encrypt": agent.get_route(os.environ["MODULE_ID"]).get("lets_encrypt", False),
    "webui_name": os.getenv("WEBUI_NAME", "Open WebUI"),
    "enable_signup": os.getenv("ENABLE_SIGNUP", "true") == "true",
    "default_user_role": os.getenv("DEFAULT_USER_ROLE", "pending"),
    "enable_openai_api": os.getenv("ENABLE_OPENAI_API", "false") == "true",
    "ollama_keep_alive": os.getenv("OLLAMA_KEEP_ALIVE", "5m"),
    "timezone": os.getenv("TZ", "UTC"),
    "url": f"https://{host}/" if host else "",
}

json.dump(config, fp=sys.stdout)
